### ISSUE TITLE
Error encoutered when installing tigre python in windows

### ISSUE THREAD

**Issue by JixiangChen-Jimmy** [CERN/TIGRE#505]
## Expected Behavior
Sucessful installation following the guidance provided.

## Actual Behavior
Encounter the error when running 'pip install .' (as I use virtual environment, I disgard the --user)
Here is the error information.
Processing c:\projects\spine_reconstruction\tigre\python
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      信息: 用提供的模式无法找到文件。
      Traceback (most recent call last):
        File "C:\Users\12873\.conda\envs\deform\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\12873\.conda\envs\deform\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\12873\.conda\envs\deform\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\12873\AppData\Local\Temp\pip-build-env-crph_69b\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\12873\AppData\Local\Temp\pip-build-env-crph_69b\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\12873\AppData\Local\Temp\pip-build-env-crph_69b\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\12873\AppData\Local\Temp\pip-build-env-crph_69b\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 124, in <module>
        File "<string>", line 105, in locate_cuda
        File "<string>", line 59, in get_cuda_version
        File "C:\Users\12873\.conda\envs\deform\lib\ntpath.py", line 78, in join
          path = os.fspath(path)
      TypeError: expected str, bytes or os.PathLike object, not NoneType
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

## Code to reproduce the problem (If applicable)

```

```

## Specifications 

  - MATLAB/python version:
  - OS:
  - CUDA version:

**Comment by AnderBiguri** [comment]
It seems that the setup code is not being able to locate CUDA. 
It does this by looking for the enviroment variable `CUDA_HOME`, running `where nvcc` in a command line, or looking for `C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.2`. Could you check if these exist/run in your machine?

**Comment by AnderBiguri** [comment]
Can not reproduce.

Closing it due to inactivity, feel free to open it again if you still have issues
